name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ozaytsev86/create-env-file@v1
      name: Create .env
      with:
        ENV_PORT: ${{ secrets.PORT }}
        ENV_DB_USER: ${{ secrets.DB_USER }}
        ENV_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ENV_DB_NAME: ${{ secrets.DB_NAME }}
        ENV_DB_HOST: ${{ secrets.DB_HOST }}
        ENV_DB_PORT: ${{ secrets.DB_PORT }}
        ENV_TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
        ENV_API_GEO: ${{ secrets.API_GEO }}
        BACK_CAPTCHA: ${{ secrets.BACK_CAPTCHA }}
        CLIENT_CAPTCHA: ${{ secrets.CLIENT_CAPTCHA }}
        API_CAPTCHA: ${{ secrets.API_CAPTCHA }}

    - uses: kenny-caldieraro/github-action-ssh-docker-compose@master
      name: Docker-Compose Remote Deployment
      with:
        ssh_host: ${{ secrets.SSH_HOST }}
        ssh_port: ${{ secrets.SSH_PORT }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh_user: ${{ secrets.SSH_USER }}
        docker_compose_prefix: oclock
        docker_compose_filename : docker-compose.yml
