- name: Copy
  uses: andstor/copycat-action@v3
  with:
    personal_token: ${{ secrets.API_TOKEN_GITHUB }}
    src_path: api/
    dst_path: /.
    dst_owner: kenny-caldieraro
    dst_repo_name: api_totum
    src_branch: main
    dst_branch: main
    clean: true
    username: kenny-caldieraro
    email: kenny.caldieraro@gmail.com